interval: 12
rpcs:
  # BSC Mainnet (ChainID 56)
  - https://bsc-dataseed.bnbchain.org
  - https://bsc-dataseed.nariox.org
  - https://bsc-dataseed.defibit.io
  - https://bsc-dataseed.ninicoin.io
  - https://bsc.nodereal.io
  - https://bsc-dataseed-public.bnbchain.org
  - https://bnb.rpc.subquery.network/public
  # BSC Testnet (ChainID 97)
  - https://bsc-testnet-dataseed.bnbchain.org
  - https://bsc-testnet.bnbchain.org
  - https://bsc-prebsc-dataseed.bnbchain.org
  - https://bsc-dataseed.bnbchain.org
